theme: jekyll-theme-dinky
title: AirTote
description: Japanese (Unofficial) Flight Information Service
lang: ja-JP
url: https://airtote.jp

logo: /images/appiconfore.png
image: /images/appiconfore.png

locale: ja_JP

defaults:
  - scope:
      path: ""
    values:
      image: /images/appiconfore.png
      twitter:
        card: summary
